# Generated by Django 4.2.5 on 2023-09-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_criados_cargo_criado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criação'),
        ),
    ]
